# Generated by Django 5.1.6 on 2025-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamedsong',
            name='album_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
