services:
  api:
    build:
      context: ./API
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./API:/app
      - ./API/static:/app/static
    env_file:
      - ./API/.env
    environment:
      - PORT=8080
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  ui:
    build:
      context: ./UI/now-playing-ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  db:
    build:
      context: ./DB
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./DB/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
