services:
  api:
    build:
      context: ./API
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./API:/app
      - ./API/static:/app/static
    env_file:
      - ./API/.env
    environment:
      - PORT=8080
  
  ui:
    build:
      context: ./UI/now-playing-ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  db:
    build:
      context: ./DB
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nowplaying
      POSTGRES_USER: nowplaying_user
      POSTGRES_PASSWORD: nowplaying_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: