services:
  api:
    build:
      context: ./API
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./API:/app
      - ./API/static:/app/static
    env_file:
      - ./API/.env
    environment:
      - PORT=8080
  
  ui:
    build:
      context: ./UI/now-playing-ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production