# Generated by Django 5.1.6 on 2025-04-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSNAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('unlocked', models.BooleanField(default=False)),
                ('unlock_time', models.DateTimeField(blank=True, null=True)),
                ('trophy_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PSNGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('total_playtime', models.CharField(blank=True, max_length=50)),
                ('first_played', models.DateTimeField(blank=True, null=True)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('img_icon_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='PSN',
        ),
        migrations.AddField(
            model_name='psnachievement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='playstation.psngame'),
        ),
    ]
