# Generated by Django 5.1.8 on 2025-05-15 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstation', '0002_psnachievement_psngame_delete_psn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='psngame',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='psn_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psngame',
            name='appid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='psngame',
            unique_together={('user', 'appid')},
        ),
    ]
