# Generated by Django 5.1.10 on 2026-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstation', '0003_psngame_user_alter_psngame_appid_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='psnachievement',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_psn_game_achievement'),
        ),
    ]
