# Generated by Django 5.1.6 on 2025-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0002_movie_certification_movie_country_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='first_aired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
