# Generated by Django 5.1.6 on 2025-03-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0003_show_certification_show_country_show_first_aired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='show',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='show',
            name='country',
        ),
        migrations.RemoveField(
            model_name='show',
            name='first_aired',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='show',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='show',
            name='network',
        ),
        migrations.RemoveField(
            model_name='show',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='show',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='show',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='show',
            name='status',
        ),
        migrations.RemoveField(
            model_name='show',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='show',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='show',
            name='votes',
        ),
    ]
