# Generated by Django 5.1.6 on 2025-03-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0004_remove_movie_certification_remove_movie_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trakt_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
