# Generated by Django 5.1.6 on 2025-03-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0005_movie_imdb_id_movie_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
