# Generated by Django 5.1.6 on 2025-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0006_episode_last_updated_at_episode_plays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='last_watched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
