# Generated by Django 5.1.6 on 2025-04-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0008_show_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='available_translations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
