# Generated by Django 5.1.8 on 2025-05-23 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0009_episode_available_translations_episode_episode_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='trakt_movies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='trakt_shows', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trakttoken',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='trakt_tokens', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='trakt_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='trakt_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('user', 'trakt_id')},
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('user', 'trakt_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trakttoken',
            unique_together={('user',)},
        ),
    ]
