# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trakt', '0010_movie_user_show_user_trakttoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='studios',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
