# Generated by Django 5.1.8 on 2025-05-15 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxgame',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='xbox_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xboxgame',
            name='appid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='xboxgame',
            unique_together={('user', 'appid')},
        ),
    ]
