# Generated by Django 5.1.8 on 2025-05-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0002_xboxgame_user_alter_xboxgame_appid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xboxgame',
            name='platform',
            field=models.CharField(max_length=255),
        ),
    ]
