# Generated by Django 5.1.8 on 2025-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0003_alter_xboxgame_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xboxachievement',
            name='achievement_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='xboxgame',
            name='total_playtime',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
