# Generated by Django 5.1.10 on 2026-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0004_alter_xboxachievement_achievement_value_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='xboxachievement',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_xbox_game_achievement'),
        ),
    ]
