# Generated by Django 5.1.6 on 2025-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('played_at', models.DateTimeField()),
                ('album_thumbnail', models.URLField(blank=True, null=True)),
                ('track_url', models.URLField(blank=True, null=True)),
                ('artists_url', models.URLField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-played_at'],
                'constraints': [models.UniqueConstraint(fields=('title', 'artist', 'played_at'), name='unique_song')],
            },
        ),
    ]
