# Generated by Django 5.1.8 on 2025-05-23 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique_song',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='music_songs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('user', 'title', 'artist', 'played_at')},
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('user', 'title', 'artist', 'played_at'), name='unique_song_per_user'),
        ),
    ]
