# Generated by Codex on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_album_mbid_song_album_thumbnail_extralarge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_thumbnail',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_thumbnail_extralarge',
            field=models.URLField(blank=True, help_text='Album art 300x300px', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_thumbnail_large',
            field=models.URLField(blank=True, help_text='Album art 174x174px', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_thumbnail_medium',
            field=models.URLField(blank=True, help_text='Album art 64x64px', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_thumbnail_small',
            field=models.URLField(blank=True, help_text='Album art 34x34px', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_lastfm_url',
            field=models.URLField(blank=True, help_text="Artist's Last.fm page URL", max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
