# Generated by Django 5.1.6 on 2025-02-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greeting',
            new_name='Steam',
        ),
    ]
