# Generated by Django 5.1.6 on 2025-02-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_rename_greeting_steam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steam',
            name='message',
        ),
        migrations.AddField(
            model_name='steam',
            name='games_data',
            field=models.JSONField(default=dict),
        ),
    ]
