# Generated by Django 5.1.6 on 2025-04-09 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0003_remove_steam_message_steam_games_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('unlocked', models.BooleanField(default=False)),
                ('unlock_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('playtime_forever', models.PositiveIntegerField(default=0)),
                ('playtime_formatted', models.CharField(blank=True, max_length=50)),
                ('img_icon_url', models.URLField(blank=True, max_length=500)),
                ('has_community_visible_stats', models.BooleanField(default=False)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('content_descriptorids', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='Steam',
        ),
        migrations.AddField(
            model_name='achievement',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='steam.game'),
        ),
    ]
