# Generated by Django 5.1.8 on 2025-05-11 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0005_rename_app_id_game_appid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steam_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='appid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('user', 'appid')},
        ),
    ]
