# Generated by Django 5.1.8 on 2025-05-11 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0006_game_user_alter_game_appid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='steam_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
