# Generated by Django 5.1.8 on 2025-06-30 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0007_alter_game_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['user', '-last_played'], name='steam_game_user_id_62bba4_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['user', '-playtime_forever'], name='steam_game_user_id_57814c_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['user', 'appid'], name='steam_game_user_id_68d670_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['last_played'], name='steam_game_last_pl_1fb56b_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['playtime_forever'], name='steam_game_playtim_b86e12_idx'),
        ),
    ]
