# Generated by Django 5.1.10 on 2026-09-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0008_game_steam_game_user_id_62bba4_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_steam_game_achievement'),
        ),
    ]
