# Generated by Django 5.1.6 on 2025-04-07 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetroAchievementsGame',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('console_id', models.IntegerField()),
                ('console_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('image_icon', models.URLField()),
                ('image_title', models.URLField()),
                ('image_ingame', models.URLField()),
                ('image_box_art', models.URLField()),
                ('last_played', models.DateTimeField()),
                ('achievements_total', models.IntegerField()),
                ('num_possible_achievements', models.IntegerField()),
                ('possible_score', models.IntegerField()),
                ('num_achieved', models.IntegerField()),
                ('score_achieved', models.IntegerField()),
                ('num_achieved_hardcore', models.IntegerField()),
                ('score_achieved_hardcore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameAchievement',
            fields=[
                ('achievement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('true_ratio', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('badge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_earned', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='retroachievements.retroachievementsgame')),
            ],
        ),
    ]
