# Generated by Django 5.1.8 on 2025-05-15 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetroAchievementsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('console_id', models.IntegerField()),
                ('console_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('image_icon', models.URLField()),
                ('image_title', models.URLField()),
                ('image_ingame', models.URLField()),
                ('image_box_art', models.URLField()),
                ('last_played', models.DateTimeField()),
                ('achievements_total', models.IntegerField()),
                ('num_possible_achievements', models.IntegerField()),
                ('possible_score', models.IntegerField()),
                ('num_achieved', models.IntegerField()),
                ('score_achieved', models.IntegerField()),
                ('num_achieved_hardcore', models.IntegerField()),
                ('score_achieved_hardcore', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retroachievements_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('true_ratio', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('badge_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_order', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_earned', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='retroachievements.retroachievementsgame')),
            ],
        ),
        migrations.AddConstraint(
            model_name='retroachievementsgame',
            constraint=models.UniqueConstraint(fields=('user', 'game_id'), name='unique_user_game'),
        ),
        migrations.AddConstraint(
            model_name='gameachievement',
            constraint=models.UniqueConstraint(fields=('game', 'achievement_id'), name='unique_game_achievement'),
        ),
    ]
