# Generated by Django 5.1.8 on 2025-06-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='genrestatistics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='genrestatistics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listeningsession',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='platformstatistics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='platformstatistics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='AchievementProgress',
        ),
        migrations.DeleteModel(
            name='GenreStatistics',
        ),
        migrations.DeleteModel(
            name='ListeningSession',
        ),
        migrations.DeleteModel(
            name='PlatformStatistics',
        ),
        migrations.DeleteModel(
            name='WatchSession',
        ),
    ]
