# Generated by Django 5.1.8 on 2025-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userapikey_key_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='service_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
