# Generated by Django 5.1.8 on 2025-06-30 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userapikey_service_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['user', 'service_name'], name='users_usera_user_id_62609b_idx'),
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['service_name'], name='users_usera_service_170daf_idx'),
        ),
        migrations.AddIndex(
            model_name='userapikey',
            index=models.Index(fields=['last_used'], name='users_usera_last_us_ea4cdb_idx'),
        ),
    ]
